#include <cctype>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <vector>

std::string create_valid_identifier(std::string filename) {
    if (filename.empty()) {
        return "_";
    }

    if (std::isdigit(static_cast<unsigned char>(filename[0]))) {
        filename.insert(filename.begin(), '_');
    }

    for (size_t i = 0; i < filename.size(); ++i) {
        if (filename[i] == '.' || filename[i] == '-') {
            filename[i] = '_';
        }
    }

    return filename;
}

std::string just_lowercase_everything(std::string str) {
    for (auto& ch : str) {
        ch = static_cast<char>(std::tolower(static_cast<unsigned char>(ch)));
    }
    return str;
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cout << "Usage: " << argv[0] << " <option> <inputfile>\n";
        std::cout << "Options:\n";
        std::cout << "\tc - Hardcode in C\n";
        std::cout << "\tcxx - Hardcode in C++\n";
        return 1;
    }

    const std::string option = just_lowercase_everything(argv[1]);

    if (option != "c" && option != "cxx") {
        std::cerr << "Invalid option \"" << option << "\"\n";
        return 1;
    }

    const std::string input_filepath = argv[2];
    std::ifstream input_file(input_filepath, std::ios::binary | std::ios::ate);
    if (input_file.fail()) {
        std::cerr << "Could not open file \"" << input_filepath << "\"\n";
        return 1;
    }

    const std::streamsize input_file_size = input_file.tellg();
    input_file.seekg(0, std::ios_base::beg);

    std::vector<unsigned char> bytes(static_cast<std::size_t>(input_file_size));
    input_file.read(reinterpret_cast<char*>(bytes.data()), bytes.size());

    const std::string input_filename = std::filesystem::path(input_filepath).filename().string();
    const std::string identifier = create_valid_identifier(input_filename);
    const std::string output_filename = input_filename + ".h";

    std::ofstream output_file(output_filename);
    output_file << "/* Generated by hardcoder. Do not edit manually. */\n";
    output_file << "#ifndef " << identifier << "_H\n";
    output_file << "#define " << identifier << "_H\n\n";
    output_file << "/* Embedded data */\n";

    if (option == "c") {
        output_file << "const unsigned char " << identifier << "[] = {\n";
    } else {
        output_file << "constexpr unsigned char " << identifier << "[] = {\n";
    }

    for (size_t i = 0; i < bytes.size(); ++i) {
        output_file << "    0x" << std::hex << std::setw(2) << std::setfill('0')
                    << static_cast<int>(bytes[i]);

        if (i + 1 != bytes.size()) {
            output_file << ",";
        }

        if ((i + 1) % 16 == 0 || i + 1 == bytes.size()) {
            output_file << "\n";
        } else {
            output_file << ' ';
        }
    }

    output_file << "};\n\n";
    output_file << "/* Size of the embedded data */\n";

    if (option == "c") {
        output_file << "const unsigned int " << identifier << "_size = " << bytes.size() << ";\n";
    } else {
        output_file << "constexpr unsigned int " << identifier << "_size = " << bytes.size() << ";\n";
    }

    output_file << "\n#endif\n";
    return 0;
}